export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  readTime: string;
  category: string;
  tags: string[];
  author: string;
}

export function getAllTags(): { tag: string; count: number }[] {
  const tagMap = new Map<string, number>();
  POSTS.forEach((p) => p.tags.forEach((t) => tagMap.set(t, (tagMap.get(t) || 0) + 1)));
  return Array.from(tagMap.entries())
    .map(([tag, count]) => ({ tag, count }))
    .sort((a, b) => b.count - a.count);
}

export function getPostsByTag(tag: string): BlogPost[] {
  return POSTS.filter((p) => p.tags.includes(tag));
}

export const TAG_LABELS: Record<string, string> = {
  "osha": "OSHA",
  "compliance": "Compliance",
  "inspection": "Inspection",
  "safety": "Safety",
  "documentation": "Documentation",
  "regulations": "Regulations",
  "checklists": "Checklists",
  "certification": "Certification",
  "mobile-crane": "Mobile Crane",
  "tower-crane": "Tower Crane",
  "overhead-crane": "Overhead Crane",
  "wire-rope": "Wire Rope",
  "rigging": "Rigging",
  "audit": "Audit",
  "penalties": "Penalties",
  "technology": "Technology",
  "templates": "Templates",
  "construction": "Construction",
  "ansi-b30": "ANSI B30",
  "load-charts": "Load Charts",
  "maintenance": "Maintenance",
  "rental": "Rental",
  "records": "Records",
  "industry": "Industry",
  "demolition": "Demolition",
  "electrical": "Electrical",
  "foundation": "Foundation",
  "liability": "Liability",
  "insurance": "Insurance",
  "near-miss": "Near Miss",
  "night-operations": "Night Operations",
  "stabilizer": "Stabilizer",
  "ndt": "NDT",
  "anti-two-block": "Anti-Two-Block",
  "fatigue": "Fatigue",
  "heat-safety": "Heat Safety",
  "clearance": "Clearance",
  "telescopic": "Telescopic",
  "load-testing": "Load Testing",
  "emergency": "Emergency",
  "pre-erection": "Pre-Erection",
  "planning": "Planning",
  "fleet-management": "Fleet Management",
  "preventive-maintenance": "Preventive Maintenance",
  "runway": "Runway",
  "bridge-crane": "Bridge Crane",
  "gantry-crane": "Gantry Crane",
  "derating": "Derating",
  "modification": "Modification",
  "drones": "Drones",
  "iot": "IoT",
  "ai": "AI",
  "toolbox-talk": "Toolbox Talk",
  "training": "Training",
  "reinspection": "Reinspection",
  "rough-terrain": "Rough Terrain",
  "all-terrain": "All-Terrain",
  "personnel-platform": "Personnel Platform",
  "petrochemical": "Petrochemical",
  "refinery": "Refinery",
  "wind-energy": "Wind Energy",
  "renewable": "Renewable",
  "knuckle-boom": "Knuckle Boom",
  "articulating": "Articulating",
  "mining": "Mining",
  "msha": "MSHA",
  "nccco": "NCCCO",
};

export const POSTS: BlogPost[] = [
  {
    slug: "crane-operator-training-program-requirements",
    title: "Crane Operator Training Program Requirements: NCCCO, CIC-P & Building an Effective Training Program",
    excerpt: "Complete guide to crane operator training program requirements including NCCCO certification paths, CIC-P accredited programs, practical exam components, employer qualification vs certification, and OSHA 1926.1427 site-specific training requirements.",
    date: "April 17, 2026",
    readTime: "14 min read",
    category: "Certification",
    tags: ["certification", "training", "compliance", "osha", "nccco"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-mining-operations",
    title: "Crane Inspection for Mining Operations: MSHA Compliance, Underground Hoists & Surface Crane Requirements",
    excerpt: "Complete guide to crane inspection for mining operations covering MSHA vs OSHA jurisdiction, 30 CFR Part 56/57 requirements, underground hoist inspection, surface crane operations, dust and corrosion effects, and dragline inspection.",
    date: "April 17, 2026",
    readTime: "14 min read",
    category: "Industry",
    tags: ["industry", "compliance", "inspection", "safety", "mining", "msha"],
    author: "cranecheck-team",
  },
  {
    slug: "knuckle-boom-crane-inspection-articulating",
    title: "Knuckle Boom & Articulating Crane Inspection: Loader Cranes, ASME B30.22 & Unique Inspection Points",
    excerpt: "Complete guide to knuckle boom and articulating crane inspection covering ASME B30.22 requirements, folding mechanism inspection, cylinder pin wear, stability analysis, and remote control system testing.",
    date: "April 17, 2026",
    readTime: "12 min read",
    category: "Inspection",
    tags: ["inspection", "compliance", "checklists", "maintenance", "knuckle-boom", "articulating"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-wind-energy-renewable",
    title: "Crane Inspection for Wind Energy & Renewable Projects: Turbine Erection, Hub Heights & Specialized Requirements",
    excerpt: "Guide to crane inspection for wind energy projects covering turbine erection crane requirements, extreme hub heights, blade installation rigging, tandem lifts for nacelles, and remote site challenges.",
    date: "April 17, 2026",
    readTime: "13 min read",
    category: "Industry",
    tags: ["industry", "construction", "inspection", "safety", "wind-energy", "renewable"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-petrochemical-refinery",
    title: "Crane Inspection for Petrochemical & Refinery Operations: Hot Work, Confined Spaces & API Standards",
    excerpt: "Guide to crane inspection for petrochemical and refinery operations covering hazardous area classifications, hot work permits, API standards, turnaround crane management, and explosion-proof requirements.",
    date: "April 17, 2026",
    readTime: "14 min read",
    category: "Industry",
    tags: ["industry", "safety", "compliance", "inspection", "petrochemical", "refinery"],
    author: "cranecheck-team",
  },
  {
    slug: "suspended-personnel-platform-inspection",
    title: "Suspended Personnel Platform Inspection: Man Basket Safety, OSHA 1926.1431 & ASME B30.23 Requirements",
    excerpt: "Complete guide to suspended personnel platform inspection including OSHA 1926.1431 compliance, ASME B30.23 standards, trial lift procedures, 50% capacity derating, communication systems, and platform construction inspection.",
    date: "April 17, 2026",
    readTime: "15 min read",
    category: "Safety",
    tags: ["safety", "compliance", "osha", "inspection", "personnel-platform"],
    author: "cranecheck-team",
  },
  {
    slug: "all-terrain-crane-inspection-guide",
    title: "All-Terrain Crane Inspection Guide: Multi-Axle Systems, Road Travel & ASME B30.5 Compliance",
    excerpt: "Comprehensive guide to all-terrain crane inspection covering multi-axle steering systems, dual-cab inspection, road travel requirements, suspension lockout, counterweight configurations, and ASME B30.5 compliance.",
    date: "April 17, 2026",
    readTime: "13 min read",
    category: "Inspection",
    tags: ["inspection", "mobile-crane", "compliance", "safety", "all-terrain"],
    author: "cranecheck-team",
  },
  {
    slug: "rough-terrain-crane-inspection-checklist",
    title: "Rough Terrain Crane Inspection Checklist: RT Crane Components, ASME B30.5 & Field Inspection Guide",
    excerpt: "Complete rough terrain crane inspection checklist covering RT-specific components, 4WD drivetrain inspection, outrigger-free operation, boom configurations, terrain assessment, and ASME B30.5 compliance requirements.",
    date: "April 17, 2026",
    readTime: "14 min read",
    category: "Checklists",
    tags: ["checklists", "mobile-crane", "inspection", "compliance", "rough-terrain"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-safety-meeting-topics-toolbox-talks",
    title: "Crane Safety Meeting Topics: 52 Toolbox Talk Ideas for Weekly Safety Meetings",
    excerpt: "52 crane safety meeting and toolbox talk topics organized by category with discussion guides. Cover every critical crane safety topic across a full year of weekly safety meetings.",
    date: "April 15, 2026",
    readTime: "15 min read",
    category: "Safety",
    tags: ["safety", "toolbox-talk", "training", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-technology-drones-iot",
    title: "Crane Inspection Technology: Drones, IoT Sensors, AI & the Future of Crane Safety",
    excerpt: "How drones, IoT sensors, AI-powered analysis, and digital inspection platforms are transforming crane inspection. Learn what technologies are ready for deployment, what's emerging, and how to evaluate ROI.",
    date: "April 15, 2026",
    readTime: "12 min read",
    category: "Technology",
    tags: ["technology", "drones", "iot", "ai"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-capacity-derating-factors",
    title: "Crane Capacity Derating: When & How to Reduce Rated Capacity for Safe Operations",
    excerpt: "Complete guide to crane capacity derating factors. Learn when to reduce crane rated capacity for wind, temperature, duty cycle, age, wear conditions, and non-standard configurations under ASME B30.5 and OSHA requirements.",
    date: "April 15, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "derating", "compliance", "load-charts"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-modification-alteration-inspection",
    title: "Crane Modifications & Alterations: Inspection Requirements, OSHA 1926.1434 & Engineering Approval",
    excerpt: "Guide to crane modification and alteration inspection requirements. Learn what constitutes a modification vs. repair under OSHA 1926.1434, manufacturer approval processes, PE requirements, and post-modification inspection and testing.",
    date: "April 15, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "modification", "osha", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "post-incident-crane-reinspection",
    title: "Post-Incident Crane Reinspection: When to Re-Inspect After Accidents, Overloads & Near-Misses",
    excerpt: "Guide to post-incident crane reinspection requirements after accidents, overloads, two-blocking events, tip-overs, and structural contact. Learn OSHA and ASME B30 requirements for returning a crane to service after an incident.",
    date: "April 15, 2026",
    readTime: "12 min read",
    category: "Safety",
    tags: ["safety", "reinspection", "osha", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "bridge-gantry-crane-inspection-checklist",
    title: "Bridge & Gantry Crane Inspection Checklist: ASME B30.2, B30.11 & OSHA 1910.179 Compliance",
    excerpt: "Complete bridge and gantry crane inspection checklist covering bridge girders, trolley mechanisms, drive systems, hoist assemblies, brakes, and electrical controls with ASME B30.2, B30.11 and OSHA 1910.179 compliance.",
    date: "April 15, 2026",
    readTime: "14 min read",
    category: "Checklists",
    tags: ["checklists", "bridge-crane", "gantry-crane", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "overhead-crane-runway-rail-inspection",
    title: "Overhead Crane Runway & Rail Inspection: Alignment, End Stops, Girder Deflection & ASME B30.2",
    excerpt: "Complete guide to overhead crane runway and rail inspection. Learn rail alignment tolerances, end stop inspection, girder deflection measurement, conductor bar safety, and ASME B30.2/OSHA 1910.179 compliance.",
    date: "April 15, 2026",
    readTime: "12 min read",
    category: "Inspection",
    tags: ["inspection", "overhead-crane", "runway", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-fleet-management-preventive-maintenance",
    title: "Crane Fleet Management: Preventive Maintenance Programs, Scheduling & OSHA Compliance",
    excerpt: "Complete guide to crane fleet management and preventive maintenance programs. Learn PM scheduling intervals, component lifecycle tracking, fleet utilization optimization, and how to build a compliance-ready maintenance program.",
    date: "April 15, 2026",
    readTime: "13 min read",
    category: "Maintenance",
    tags: ["maintenance", "fleet-management", "preventive-maintenance", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-load-testing-requirements",
    title: "Crane Load Testing Requirements: Proof Load Tests, ASME B30.5 & OSHA 1926.1412(c) Guide",
    excerpt: "Complete guide to crane load test requirements including when load tests are required, ASME B30.5-5.2.2 procedures, proof load vs rated load distinctions, percentage requirements, documentation, and OSHA 1926.1412(c) compliance.",
    date: "April 4, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "load-testing", "safety", "regulations"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-emergency-shutdown-procedures",
    title: "Crane Emergency Shutdown Procedures: Rescue Plans, Severe Weather & OSHA 1926.1424 Compliance",
    excerpt: "Complete guide to crane emergency shutdown procedures by crane type, operator rescue and evacuation plans, severe weather response per ASME B30.5-5.3.3.2, fire and power failure protocols, and OSHA 1926.1424 emergency action plan requirements.",
    date: "April 4, 2026",
    readTime: "12 min read",
    category: "Safety",
    tags: ["safety", "emergency", "osha", "checklists"],
    author: "nolan-terry",
  },
  {
    slug: "crane-pre-erection-planning-guide",
    title: "Crane Pre-Erection Planning Guide: Site Surveys, Foundations, Permits & A/D Director Requirements",
    excerpt: "Complete guide to crane pre-erection planning including site surveys, soil bearing capacity testing, foundation design per ASME B30.5-5.1.1, utility locates per 811/OSHA 1926.1408, FAA notification, permits, and A/D director requirements per OSHA 1926.1404.",
    date: "April 4, 2026",
    readTime: "13 min read",
    category: "Planning",
    tags: ["construction", "pre-erection", "foundation", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "telescopic-boom-crane-inspection-checklist",
    title: "Telescopic Boom Crane Inspection Checklist: Section-by-Section Guide for Hydraulic Boom Cranes",
    excerpt: "Complete telescopic boom crane inspection checklist covering wear pads, boom section alignment, hydraulic cylinder inspection, pin and bushing checks, and ASME B30.5 compliance requirements.",
    date: "April 4, 2026",
    readTime: "12 min read",
    category: "Inspection",
    tags: ["inspection", "telescopic", "mobile-crane", "checklists"],
    author: "nolan-terry",
  },
  {
    slug: "crane-clearance-requirements-structures",
    title: "Crane Clearance Requirements: OSHA 1926.1408 Power Lines, Building Proximity & Pedestrian Zones",
    excerpt: "Complete guide to crane clearance requirements including OSHA 1926.1408 power line distances, building proximity rules, pedestrian exclusion zones, and underground utility clearance documentation.",
    date: "April 4, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "clearance", "safety"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-hot-weather-operations",
    title: "Crane Hot Weather Operations: Heat Effects on Steel, Hydraulics & Operator Safety",
    excerpt: "Guide to crane operations in extreme heat covering heat effects on crane steel and hydraulics, operator heat illness prevention, OSHA heat guidelines, load chart considerations, and fluid management.",
    date: "April 4, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "heat-safety", "maintenance", "osha"],
    author: "nolan-terry",
  },
  {
    slug: "crane-operator-fatigue-management",
    title: "Crane Operator Fatigue Management: Work Hours, Rest Requirements & Safety Programs",
    excerpt: "Comprehensive guide to crane operator fatigue management including work hour best practices, OSHA general duty clause requirements, fatigue risk assessment, impairment signs, and management programs.",
    date: "April 4, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "fatigue", "osha", "certification"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-anti-two-block-safety",
    title: "Anti-Two-Block (ATB) Safety Devices: ASME B30.5 Requirements, Inspection & Testing",
    excerpt: "Complete guide to anti-two-block safety devices for cranes including ASME B30.5 ATB requirements, device types, inspection and testing procedures, failure modes, and OSHA citation history.",
    date: "April 4, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "anti-two-block", "inspection", "ansi-b30"],
    author: "nolan-terry",
  },
  {
    slug: "crane-night-operations-lighting",
    title: "Crane Night Operations & Lighting Requirements: OSHA 1926.56, Visibility & Signaling Standards",
    excerpt: "Complete guide to crane night operations including OSHA 1926.56 lighting requirements, minimum illumination levels, obstruction lighting, signal person visibility standards, and night shift safety protocols.",
    date: "April 4, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "osha", "night-operations", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "crane-stabilizer-pad-requirements",
    title: "Crane Stabilizer Pad & Cribbing Requirements: Load Distribution, Mat Sizing & Soil Pressure",
    excerpt: "Complete guide to crane stabilizer pad and cribbing requirements. Learn outrigger pad sizing calculations, load distribution principles, soil bearing pressure assessment, cribbing stack design, and OSHA compliance.",
    date: "April 4, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "mobile-crane", "stabilizer", "construction"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-near-miss-reporting",
    title: "Crane Near-Miss Reporting: Incident Tracking, Root Cause Analysis & Safety Culture Programs",
    excerpt: "How to implement effective near-miss reporting programs for crane operations. Learn incident tracking systems, root cause analysis methods, safety culture development, and OSHA voluntary reporting guidelines.",
    date: "April 4, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "near-miss", "documentation", "compliance"],
    author: "nolan-terry",
  },
  {
    slug: "crane-insurance-requirements-coverage",
    title: "Crane Insurance Requirements: Liability Coverage, Inland Marine & Riggers Insurance Guide",
    excerpt: "Complete guide to crane insurance requirements including general liability, inland marine coverage, riggers insurance, builders risk, certificate of insurance requirements, and how inspection records affect premiums.",
    date: "April 4, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "insurance", "rental", "documentation"],
    author: "cranecheck-team",
  },
  {
    slug: "osha-multi-employer-crane-liability",
    title: "OSHA Multi-Employer Crane Liability: GC, Crane Owner & Controlling Employer Responsibilities",
    excerpt: "Understanding multi-employer worksite crane liability under OSHA. Learn who is responsible for crane safety — general contractors, crane owners, operators, and controlling employers — and how citations are allocated.",
    date: "April 4, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "liability", "regulations"],
    author: "nolan-terry",
  },
  {
    slug: "crane-foundation-pier-requirements",
    title: "Crane Foundation & Pier Requirements: Soil Bearing, Anchor Bolts & Engineering Standards",
    excerpt: "Complete guide to crane foundation and pier requirements for fixed and tower cranes. Learn soil bearing capacity calculations, anchor bolt specifications, engineering review requirements, and OSHA compliance standards.",
    date: "April 4, 2026",
    readTime: "12 min read",
    category: "Compliance",
    tags: ["compliance", "tower-crane", "foundation", "construction"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-electrical-system-inspection",
    title: "Crane Electrical System Inspection: Limit Switches, LMI/RCI, Anti-Two-Block & Controls",
    excerpt: "Complete guide to crane electrical system inspection covering limit switches, anti-two-block devices, load moment indicators (LMI), rated capacity indicators (RCI), pendant controls, and grounding requirements.",
    date: "April 4, 2026",
    readTime: "11 min read",
    category: "Inspection",
    tags: ["inspection", "electrical", "safety", "maintenance"],
    author: "nolan-terry",
  },
  {
    slug: "crane-boom-inspection-guide",
    title: "Crane Boom Inspection Guide: Telescopic & Lattice Boom Procedures, Cracks & ASME B30.5",
    excerpt: "Complete guide to crane boom inspection procedures for telescopic and lattice booms. Learn crack detection, pin wear assessment, structural integrity checks, and ASME B30.5 compliance requirements.",
    date: "April 4, 2026",
    readTime: "12 min read",
    category: "Inspection",
    tags: ["inspection", "safety", "mobile-crane", "ndt"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-swing-radius-safety-zones",
    title: "Crane Swing Radius Protection: Safety Zones, Barricades & Worker Protection",
    excerpt: "Struck-by incidents from crane swing are among the deadliest construction hazards. Learn OSHA requirements for swing radius protection, safety zone establishment, barricade placement, and worker exclusion protocols.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "osha", "construction", "regulations"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-assembly-disassembly-safety",
    title: "Crane Assembly & Disassembly Safety: A/D Director Requirements & OSHA Compliance",
    excerpt: "Crane assembly and disassembly are among the most dangerous phases of crane operations. Learn A/D director qualifications, OSHA planning requirements, crew communication protocols, and documentation best practices.",
    date: "April 2, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "safety", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "crane-hook-inspection-criteria",
    title: "Crane Hook Inspection: Deformation Limits, NDT Testing & Replacement Criteria",
    excerpt: "Crane hooks are single-point-of-failure components. Learn ASME B30.10 inspection criteria, throat opening deformation limits, twist measurement, NDT testing methods, and hook replacement standards.",
    date: "April 2, 2026",
    readTime: "11 min read",
    category: "Inspection",
    tags: ["inspection", "safety", "compliance", "ndt"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-tandem-lift-requirements",
    title: "Tandem Crane Lifts: Planning, Engineering & Multi-Crane Coordination Requirements",
    excerpt: "Tandem lifts multiply crane risks exponentially. Learn engineering requirements, load distribution calculations, communication protocols, OSHA multi-crane coordination rules, and critical lift planning for tandem operations.",
    date: "April 2, 2026",
    readTime: "12 min read",
    category: "Safety",
    tags: ["safety", "compliance", "rigging", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "crane-cold-weather-operations",
    title: "Crane Cold Weather Operations: Winter Safety, Steel Brittle Points & Anti-Freeze Protocols",
    excerpt: "Cold weather creates hidden crane hazards — brittle steel fractures, hydraulic sluggishness, ice loading, and reduced operator dexterity. Learn temperature limits, warm-up procedures, and winter inspection protocols.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "maintenance", "construction", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "crawler-crane-inspection-checklist",
    title: "Crawler Crane Inspection Checklist: Tracks, Undercarriage & OSHA Compliance",
    excerpt: "Crawler cranes have unique inspection requirements — track tension, roller wear, sprocket condition, and undercarriage integrity. Get the complete inspection checklist with OSHA and manufacturer compliance points.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Checklists",
    tags: ["checklists", "inspection", "compliance", "mobile-crane"],
    author: "nolan-terry",
  },
  {
    slug: "hydraulic-crane-inspection-guide",
    title: "Hydraulic Crane Inspection: Cylinders, Hoses, Pumps & Fluid Analysis",
    excerpt: "Hydraulic system failures cause catastrophic crane incidents. Learn how to inspect cylinders, hoses, pumps, filters, and fluid — plus oil analysis techniques that predict failures before they happen.",
    date: "April 2, 2026",
    readTime: "11 min read",
    category: "Inspection",
    tags: ["inspection", "mobile-crane", "maintenance", "safety"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-wind-speed-limits",
    title: "Crane Wind Speed Limits: When to Stop Operations & Weather Safety Protocols",
    excerpt: "Wind is the most unpredictable crane hazard. Learn manufacturer wind speed limits by crane type, anemometer requirements, gust factor calculations, and OSHA weather shutdown procedures.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "mobile-crane", "tower-crane", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "crane-power-line-safety",
    title: "Crane Power Line Safety: Minimum Distances, Electrocution Prevention & OSHA Standards",
    excerpt: "Electrocution from power line contact is the second leading cause of crane fatalities. Learn OSHA minimum approach distances, voltage identification, spotter requirements, and the Table A clearance rules.",
    date: "April 2, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "osha", "construction", "regulations"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-signal-person-requirements",
    title: "Crane Signal Person Requirements: Certification, Hand Signals & OSHA Rules",
    excerpt: "Every crane lift requiring signals needs a qualified signal person. Learn OSHA certification requirements, standard hand signals, communication protocols, and qualification testing procedures.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Certification",
    tags: ["certification", "safety", "osha", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "crane-ground-conditions-setup",
    title: "Crane Ground Conditions and Site Setup: OSHA Requirements for Safe Operation",
    excerpt: "Ground failure is the leading cause of crane tip-overs on construction sites. Learn OSHA ground condition requirements, soil bearing capacity assessment, outrigger pad sizing, and site preparation best practices.",
    date: "March 26, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "osha", "construction", "mobile-crane"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-software-roi",
    title: "Crane Inspection Software ROI: The Business Case for Going Digital",
    excerpt: "Digital crane inspection software pays for itself within months. See the real numbers on time savings, compliance cost reduction, and risk mitigation that make the business case for going paperless.",
    date: "March 26, 2026",
    readTime: "11 min read",
    category: "Technology",
    tags: ["technology", "inspection", "documentation", "compliance"],
    author: "nolan-terry",
  },
  {
    slug: "crane-inspection-demolition-projects",
    title: "Crane Inspection for Demolition Projects: Special Requirements You Can't Ignore",
    excerpt: "Demolition crane operations face unique hazards — falling debris, unstable structures, dust exposure, and dynamic load changes. Here are the special inspection requirements OSHA mandates for demolition sites.",
    date: "March 26, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "construction", "inspection", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "lattice-boom-crane-inspection",
    title: "Lattice Boom Crane Inspection: Complete Guide for Crawler and Truck Cranes",
    excerpt: "Lattice boom cranes require specialized inspection procedures that differ significantly from hydraulic telescopic cranes. Complete inspection guide covering boom sections, pins, lacings, pendants, and structural connections.",
    date: "March 26, 2026",
    readTime: "12 min read",
    category: "Inspection",
    tags: ["inspection", "safety", "maintenance", "checklists"],
    author: "nolan-terry",
  },
  {
    slug: "ansi-b30-vs-osha-crane-standards",
    title: "ANSI B30 vs OSHA: Understanding Crane Inspection Standard Differences",
    excerpt: "OSHA sets the legal minimum, ANSI B30 defines technical excellence — but the relationship between these standards is more complex than most crane companies realize. Here's how they compare and when each applies.",
    date: "March 26, 2026",
    readTime: "13 min read",
    category: "Regulations",
    tags: ["regulations", "ansi-b30", "osha", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-outrigger-inspection-setup",
    title: "Crane Outrigger Inspection and Setup: Preventing the #1 Cause of Tip-Overs",
    excerpt: "Outrigger failure and improper setup cause more crane tip-overs than any other single factor. Complete guide to outrigger inspection criteria, proper deployment procedures, and ground bearing pressure calculations.",
    date: "March 26, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "inspection", "mobile-crane", "checklists"],
    author: "nolan-terry",
  },
  {
    slug: "third-party-crane-inspection",
    title: "Third-Party Crane Inspection: When You Need an Outside Inspector",
    excerpt: "When do you need a third-party crane inspector vs. in-house? Understand the regulatory triggers, insurance requirements, and business situations that mandate independent crane inspections.",
    date: "March 26, 2026",
    readTime: "11 min read",
    category: "Inspection",
    tags: ["inspection", "compliance", "safety", "certification"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-lift-plan-requirements",
    title: "Crane Lift Plan Requirements: What Every Contractor Must Document",
    excerpt: "Every crane lift needs a plan — but critical lifts require formal documentation that most contractors get wrong. Complete guide to lift plan requirements, critical lift thresholds, and what OSHA expects in your documentation.",
    date: "March 26, 2026",
    readTime: "12 min read",
    category: "Safety",
    tags: ["safety", "documentation", "compliance", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "conexpo-2026-crane-inspection-technology",
    title: "ConExpo 2026: Why Crane Inspection Is Finally Going Digital",
    excerpt: "ConExpo-CON/AGG 2026 is showcasing the most advanced crane technology ever built. But most crane companies still track inspections on paper. That disconnect is closing fast.",
    date: "March 9, 2026",
    readTime: "8 min read",
    category: "Industry",
    tags: ["industry", "technology", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "annual-crane-inspection-requirements",
    title: "Annual Crane Inspection Requirements: What OSHA and ANSI B30 Actually Require",
    excerpt: "There are three tiers of crane inspections — frequent, periodic, and annual. Most companies get the first two right and completely botch the annual. Here's what the standards actually say, who's qualified to perform them, and what you need to document.",
    date: "March 9, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "ansi-b30", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "qualified-vs-competent-person-crane",
    title: "Qualified Person vs. Competent Person: Who Can Inspect Your Crane?",
    excerpt: "OSHA uses these terms precisely — and they don't mean the same thing. If the wrong person is signing off on your inspections, those inspections are effectively invalid.",
    date: "March 9, 2026",
    readTime: "9 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "certification", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-maintenance-log-requirements",
    title: "Crane Maintenance Log Requirements: What OSHA Expects in Your Records",
    excerpt: "OSHA 1926.1417 has specific maintenance documentation requirements that most crane companies overlook — until an auditor or a plaintiff's attorney comes looking.",
    date: "March 9, 2026",
    readTime: "10 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "maintenance", "documentation"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-rental-inspection-obligations",
    title: "Who's Responsible for Inspecting a Rented Crane? OSHA Rules Explained",
    excerpt: "OSHA's multi-employer worksite rules create complex inspection obligations for rented cranes. Both the rental company and the contractor can be cited.",
    date: "March 9, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "osha", "rental", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-record-retention",
    title: "How Long Must You Keep Crane Inspection Records? Retention Guide",
    excerpt: "Crane inspection record retention requirements under OSHA, ANSI B30, and state regulations. What to keep, how long, and why digital records eliminate retention risk.",
    date: "March 9, 2026",
    readTime: "8 min read",
    category: "Compliance",
    tags: ["compliance", "records", "documentation", "regulations"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-accident-investigation-documentation",
    title: "Crane Accident Investigation: Documentation That Protects Your Company",
    excerpt: "When a crane incident happens, what you document in the first 24 hours determines whether you face a standard citation or a willful violation. Covers OSHA reporting timelines, scene documentation, and how your inspection history becomes your defense.",
    date: "March 8, 2026",
    readTime: "13 min read",
    category: "Safety",
    tags: ["safety", "osha", "documentation", "penalties"],
    author: "cranecheck-team",
  },
  {
    slug: "rigging-inspection-requirements",
    title: "Rigging Inspection Requirements: Slings, Shackles, and Hardware",
    excerpt: "Complete OSHA rigging inspection requirements under 29 CFR 1926.251. Covers wire rope sling criteria, synthetic web sling checks, chain sling inspection, shackle load ratings, and removal-from-service standards.",
    date: "March 8, 2026",
    readTime: "11 min read",
    category: "Rigging",
    tags: ["rigging", "osha", "inspection", "safety"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-report-template",
    title: "Crane Inspection Report Template: What Inspectors Actually Need",
    excerpt: "Most crane inspection forms are missing critical fields. Learn what a compliant crane inspection report must contain, common documentation gaps that trigger OSHA citations, and why static templates create more risk than they solve.",
    date: "March 8, 2026",
    readTime: "10 min read",
    category: "Templates",
    tags: ["templates", "inspection", "documentation", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "overhead-crane-inspection-frequency",
    title: "Overhead Crane Inspection Frequency: OSHA vs ASME Requirements",
    excerpt: "How often should you inspect overhead cranes? Break down daily, monthly, quarterly, and annual inspection schedules under OSHA 1910.179 and ASME B30.2, plus service classification guidance.",
    date: "March 8, 2026",
    readTime: "12 min read",
    category: "Compliance",
    tags: ["overhead-crane", "compliance", "osha", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-load-chart-documentation",
    title: "How to Document Crane Load Charts for OSHA Compliance",
    excerpt: "Complete guide to crane load chart documentation requirements. Learn rated capacity recording, boom length tracking, digital load chart management, and how to prevent citations with proper documentation systems.",
    date: "March 8, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "load-charts", "documentation", "osha"],
    author: "cranecheck-team",
  },
  {
    slug: "mobile-crane-inspection-checklist",
    title: "Mobile Crane Inspection Checklist: Complete Field Guide",
    excerpt: "A comprehensive pre-operation inspection checklist for all-terrain, rough-terrain, and truck-mounted mobile cranes. Covers hydraulic systems, outriggers, load moment indicators, wire rope, and all OSHA-required inspection items for daily compliance.",
    date: "March 7, 2026",
    readTime: "11 min read",
    category: "Checklists",
    tags: ["mobile-crane", "checklists", "inspection", "osha"],
    author: "nolan-terry",
  },
  {
    slug: "crane-inspection-penalties-fines",
    title: "OSHA Crane Inspection Penalties: What Non-Compliance Actually Costs",
    excerpt: "The real financial impact of OSHA crane inspection violations in 2026. From $16,550 serious violations to $165,514 willful violations, plus real citation examples and how penalties compound when multiple cranes and violations are involved.",
    date: "March 6, 2026",
    readTime: "12 min read",
    category: "Compliance",
    tags: ["compliance", "penalties", "osha", "regulations"],
    author: "nolan-terry",
  },
  {
    slug: "tower-crane-inspection-requirements",
    title: "Tower Crane Inspection Requirements: Erection to Dismantling",
    excerpt: "Comprehensive guide to tower crane inspection requirements throughout the crane lifecycle. From foundation engineering review and pre-erection inspections to climbing procedures, monthly/annual inspections, and dismantling requirements under OSHA 29 CFR 1926 Subpart CC.",
    date: "March 5, 2026",
    readTime: "13 min read",
    category: "Regulations",
    tags: ["tower-crane", "regulations", "osha", "inspection"],
    author: "nolan-terry",
  },
  {
    slug: "crane-wire-rope-inspection-guide",
    title: "Crane Wire Rope Inspection: When to Replace and What to Look For",
    excerpt: "Comprehensive guide to crane wire rope inspection based on ASME B30.5 standards. Learn broken wire replacement thresholds, diameter reduction limits, corrosion assessment criteria, heat damage identification, and proper end connection inspection techniques.",
    date: "March 4, 2026",
    readTime: "12 min read",
    category: "Safety",
    tags: ["wire-rope", "safety", "inspection", "ansi-b30"],
    author: "nolan-terry",
  },
  {
    slug: "crane-operator-certification-requirements",
    title: "Crane Operator Certification Requirements: NCCCO, CIC, and State Rules",
    excerpt: "Complete guide to crane operator certification requirements under OSHA's 2026 mandate. Compare NCCCO, CIC-Crane, and NCCER programs, understand state-specific requirements, recertification timelines, and develop compliant operator qualification programs.",
    date: "March 3, 2026",
    readTime: "13 min read",
    category: "Compliance",
    tags: ["certification", "compliance", "osha", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "osha-crane-inspection-requirements",
    title: "OSHA Crane Inspection Requirements: The Complete 2026 Guide",
    excerpt: "Everything you need to know about OSHA's crane inspection requirements under 29 CFR 1926.1412 and 29 CFR 1910.179 — inspection types, frequencies, documentation requirements, and how to stay compliant.",
    date: "March 1, 2026",
    readTime: "12 min read",
    category: "Compliance",
    tags: ["osha", "compliance", "inspection", "regulations"],
    author: "nolan-terry",
  },
  {
    slug: "daily-crane-inspection-checklist",
    title: "Daily Crane Inspection Checklist: What OSHA Actually Requires",
    excerpt: "A detailed breakdown of the OSHA-required daily crane inspection checklist items under 29 CFR 1926.1412(d). Know exactly what your operators need to check before every shift.",
    date: "February 22, 2026",
    readTime: "10 min read",
    category: "Checklists",
    tags: ["checklists", "osha", "inspection", "compliance"],
    author: "nolan-terry",
  },
  {
    slug: "crane-inspection-software-vs-paper",
    title: "Crane Inspection Software vs Paper Logs: Why Digital Wins",
    excerpt: "Paper crane inspection logs are a liability. Digital inspection software eliminates lost records, illegible handwriting, and audit-day panic. Here's the full comparison.",
    date: "February 15, 2026",
    readTime: "9 min read",
    category: "Technology",
    tags: ["technology", "inspection", "documentation", "compliance"],
    author: "nolan-terry",
  },
  {
    slug: "osha-crane-audit-preparation",
    title: "How to Prepare for an OSHA Crane Audit",
    excerpt: "OSHA crane audits don't have to be stressful. Learn what inspectors look for, which records they'll request, and how to be ready before they arrive.",
    date: "February 8, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["audit", "osha", "compliance", "documentation"],
    author: "nolan-terry",
  },
  {
    slug: "29-cfr-1926-1412-explained",
    title: "29 CFR 1926.1412 Explained: Pre-Shift Crane Inspection Rules",
    excerpt: "A plain-English breakdown of 29 CFR 1926.1412 — the OSHA standard that governs crane inspections on construction sites. What it requires, who's responsible, and how to comply.",
    date: "February 1, 2026",
    readTime: "13 min read",
    category: "Regulations",
    tags: ["regulations", "osha", "construction", "inspection"],
    author: "nolan-terry",
  },
  {
    slug: "crane-signal-person-requirements",
    title: "Crane Signal Person Requirements: Qualifications, Hand Signals & OSHA Rules",
    excerpt: "Complete guide to crane signal person qualifications — who qualifies, OSHA & ASME B30.3 rules, standard hand signals, training requirements, and common compliance violations.",
    date: "April 19, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "osha", "training", "operations"],
    author: "nolan-terry",
  },
  {
    slug: "crane-load-chart-reading-guide",
    title: "How to Read a Crane Load Chart: A Step-by-Step Guide for Operators & Inspectors",
    excerpt: "Learn how to read a crane load chart step by step — understand gross vs net capacity, radius vs boom length, deductions, quadrant limitations, and common misreads that lead to overloading.",
    date: "April 19, 2026",
    readTime: "12 min read",
    category: "Operations",
    tags: ["operations", "safety", "training", "equipment"],
    author: "nolan-terry",
  },
  {
    slug: "crawler-crane-inspection-checklist",
    title: "Crawler Crane Inspection Checklist: Complete Guide for Compliance",
    excerpt: "A comprehensive crawler crane inspection checklist covering tracks, undercarriage, boom sections, hydraulics, electrical, and operator cab — aligned with OSHA and ANSI/ASME B30.5 requirements.",
    date: "April 19, 2026",
    readTime: "13 min read",
    category: "Inspection",
    tags: ["inspection", "compliance", "crawler-crane", "checklist"],
    author: "nolan-terry",
  },
  {
    slug: "crane-boom-inspection-deficiency-guide",
    title: "Crane Boom Inspection: Common Deficiencies & What to Look For",
    excerpt: "A detailed guide to crane boom inspection — common deficiencies in lattice and hydraulic booms, visual inspection points, NDT methods, pin wear, sheave inspection, and documentation.",
    date: "April 19, 2026",
    readTime: "12 min read",
    category: "Inspection",
    tags: ["inspection", "equipment", "deficiency", "boom"],
    author: "nolan-terry",
  },
  {
    slug: "crane-insurance-requirements-contractors",
    title: "Crane Insurance Requirements: What Contractors & Owners Need to Know",
    excerpt: "Understand crane insurance requirements — types of coverage (GL, inland marine, riggers liability), minimum limits, certificates of insurance, and how inspection documentation affects claims.",
    date: "April 19, 2026",
    readTime: "11 min read",
    category: "Business",
    tags: ["business", "insurance", "compliance", "risk"],
    author: "nolan-terry",
  },
  {
    slug: "crane-winter-cold-weather-operations",
    title: "Crane Operations in Cold Weather: Safety, Inspection & Operational Limits",
    excerpt: "Guide to cold weather crane operations — steel brittleness, hydraulic fluid considerations, wire rope in cold, warm-up procedures, reduced capacity, and cold weather inspection checklist additions.",
    date: "April 19, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "operations", "weather", "inspection"],
    author: "nolan-terry",
  },
  {
    slug: "crane-ground-bearing-pressure-calculations",
    title: "Crane Ground Bearing Pressure: Calculations, Mat Requirements & Site Assessment",
    excerpt: "Learn how to calculate crane ground bearing pressure, size outrigger pads and crane mats, assess soil bearing capacity, and avoid ground failures that lead to crane tip-overs.",
    date: "April 19, 2026",
    readTime: "13 min read",
    category: "Engineering",
    tags: ["engineering", "safety", "operations", "site-planning"],
    author: "nolan-terry",
  },
  {
    slug: "crane-inspection-drone-technology",
    title: "Using Drones for Crane Inspection: Technology, Regulations & Best Practices",
    excerpt: "How drones are used in crane inspection — where they add value, FAA Part 107 requirements, camera and sensor capabilities, limitations, integration with inspection reports, and cost-benefit analysis.",
    date: "April 19, 2026",
    readTime: "11 min read",
    category: "Technology",
    tags: ["technology", "inspection", "innovation", "equipment"],
    author: "nolan-terry",
  },
];

export function getPostsByAuthor(authorSlug: string): BlogPost[] {
  return POSTS.filter(p => p.author === authorSlug);
}
