export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  readTime: string;
  category: string;
  tags: string[];
  author: string;
}

export function getAllTags(): { tag: string; count: number }[] {
  const tagMap = new Map<string, number>();
  POSTS.forEach((p) => p.tags.forEach((t) => tagMap.set(t, (tagMap.get(t) || 0) + 1)));
  return Array.from(tagMap.entries())
    .map(([tag, count]) => ({ tag, count }))
    .sort((a, b) => b.count - a.count);
}

export function getPostsByTag(tag: string): BlogPost[] {
  return POSTS.filter((p) => p.tags.includes(tag));
}

export const TAG_LABELS: Record<string, string> = {
  "osha": "OSHA",
  "compliance": "Compliance",
  "inspection": "Inspection",
  "safety": "Safety",
  "documentation": "Documentation",
  "regulations": "Regulations",
  "checklists": "Checklists",
  "certification": "Certification",
  "mobile-crane": "Mobile Crane",
  "tower-crane": "Tower Crane",
  "overhead-crane": "Overhead Crane",
  "wire-rope": "Wire Rope",
  "rigging": "Rigging",
  "audit": "Audit",
  "penalties": "Penalties",
  "technology": "Technology",
  "templates": "Templates",
  "construction": "Construction",
  "ansi-b30": "ANSI B30",
  "load-charts": "Load Charts",
  "maintenance": "Maintenance",
  "rental": "Rental",
  "records": "Records",
  "industry": "Industry",
  "demolition": "Demolition",
};

export const POSTS: BlogPost[] = [
  {
    slug: "crane-swing-radius-safety-zones",
    title: "Crane Swing Radius Protection: Safety Zones, Barricades & Worker Protection",
    excerpt: "Struck-by incidents from crane swing are among the deadliest construction hazards. Learn OSHA requirements for swing radius protection, safety zone establishment, barricade placement, and worker exclusion protocols.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "osha", "construction", "regulations"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-assembly-disassembly-safety",
    title: "Crane Assembly & Disassembly Safety: A/D Director Requirements & OSHA Compliance",
    excerpt: "Crane assembly and disassembly are among the most dangerous phases of crane operations. Learn A/D director qualifications, OSHA planning requirements, crew communication protocols, and documentation best practices.",
    date: "April 2, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "safety", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "crane-hook-inspection-criteria",
    title: "Crane Hook Inspection: Deformation Limits, NDT Testing & Replacement Criteria",
    excerpt: "Crane hooks are single-point-of-failure components. Learn ASME B30.10 inspection criteria, throat opening deformation limits, twist measurement, NDT testing methods, and hook replacement standards.",
    date: "April 2, 2026",
    readTime: "11 min read",
    category: "Inspection",
    tags: ["inspection", "safety", "compliance", "ndt"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-tandem-lift-requirements",
    title: "Tandem Crane Lifts: Planning, Engineering & Multi-Crane Coordination Requirements",
    excerpt: "Tandem lifts multiply crane risks exponentially. Learn engineering requirements, load distribution calculations, communication protocols, OSHA multi-crane coordination rules, and critical lift planning for tandem operations.",
    date: "April 2, 2026",
    readTime: "12 min read",
    category: "Safety",
    tags: ["safety", "compliance", "rigging", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "crane-cold-weather-operations",
    title: "Crane Cold Weather Operations: Winter Safety, Steel Brittle Points & Anti-Freeze Protocols",
    excerpt: "Cold weather creates hidden crane hazards — brittle steel fractures, hydraulic sluggishness, ice loading, and reduced operator dexterity. Learn temperature limits, warm-up procedures, and winter inspection protocols.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "maintenance", "construction", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "crawler-crane-inspection-checklist",
    title: "Crawler Crane Inspection Checklist: Tracks, Undercarriage & OSHA Compliance",
    excerpt: "Crawler cranes have unique inspection requirements — track tension, roller wear, sprocket condition, and undercarriage integrity. Get the complete inspection checklist with OSHA and manufacturer compliance points.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Checklists",
    tags: ["checklists", "inspection", "compliance", "mobile-crane"],
    author: "nolan-terry",
  },
  {
    slug: "hydraulic-crane-inspection-guide",
    title: "Hydraulic Crane Inspection: Cylinders, Hoses, Pumps & Fluid Analysis",
    excerpt: "Hydraulic system failures cause catastrophic crane incidents. Learn how to inspect cylinders, hoses, pumps, filters, and fluid — plus oil analysis techniques that predict failures before they happen.",
    date: "April 2, 2026",
    readTime: "11 min read",
    category: "Inspection",
    tags: ["inspection", "mobile-crane", "maintenance", "safety"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-wind-speed-limits",
    title: "Crane Wind Speed Limits: When to Stop Operations & Weather Safety Protocols",
    excerpt: "Wind is the most unpredictable crane hazard. Learn manufacturer wind speed limits by crane type, anemometer requirements, gust factor calculations, and OSHA weather shutdown procedures.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "mobile-crane", "tower-crane", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "crane-power-line-safety",
    title: "Crane Power Line Safety: Minimum Distances, Electrocution Prevention & OSHA Standards",
    excerpt: "Electrocution from power line contact is the second leading cause of crane fatalities. Learn OSHA minimum approach distances, voltage identification, spotter requirements, and the Table A clearance rules.",
    date: "April 2, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "osha", "construction", "regulations"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-signal-person-requirements",
    title: "Crane Signal Person Requirements: Certification, Hand Signals & OSHA Rules",
    excerpt: "Every crane lift requiring signals needs a qualified signal person. Learn OSHA certification requirements, standard hand signals, communication protocols, and qualification testing procedures.",
    date: "April 2, 2026",
    readTime: "10 min read",
    category: "Certification",
    tags: ["certification", "safety", "osha", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "crane-ground-conditions-setup",
    title: "Crane Ground Conditions and Site Setup: OSHA Requirements for Safe Operation",
    excerpt: "Ground failure is the leading cause of crane tip-overs on construction sites. Learn OSHA ground condition requirements, soil bearing capacity assessment, outrigger pad sizing, and site preparation best practices.",
    date: "March 26, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "osha", "construction", "mobile-crane"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-software-roi",
    title: "Crane Inspection Software ROI: The Business Case for Going Digital",
    excerpt: "Digital crane inspection software pays for itself within months. See the real numbers on time savings, compliance cost reduction, and risk mitigation that make the business case for going paperless.",
    date: "March 26, 2026",
    readTime: "11 min read",
    category: "Technology",
    tags: ["technology", "inspection", "documentation", "compliance"],
    author: "nolan-terry",
  },
  {
    slug: "crane-inspection-demolition-projects",
    title: "Crane Inspection for Demolition Projects: Special Requirements You Can't Ignore",
    excerpt: "Demolition crane operations face unique hazards — falling debris, unstable structures, dust exposure, and dynamic load changes. Here are the special inspection requirements OSHA mandates for demolition sites.",
    date: "March 26, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "construction", "inspection", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "lattice-boom-crane-inspection",
    title: "Lattice Boom Crane Inspection: Complete Guide for Crawler and Truck Cranes",
    excerpt: "Lattice boom cranes require specialized inspection procedures that differ significantly from hydraulic telescopic cranes. Complete inspection guide covering boom sections, pins, lacings, pendants, and structural connections.",
    date: "March 26, 2026",
    readTime: "12 min read",
    category: "Inspection",
    tags: ["inspection", "safety", "maintenance", "checklists"],
    author: "nolan-terry",
  },
  {
    slug: "ansi-b30-vs-osha-crane-standards",
    title: "ANSI B30 vs OSHA: Understanding Crane Inspection Standard Differences",
    excerpt: "OSHA sets the legal minimum, ANSI B30 defines technical excellence — but the relationship between these standards is more complex than most crane companies realize. Here's how they compare and when each applies.",
    date: "March 26, 2026",
    readTime: "13 min read",
    category: "Regulations",
    tags: ["regulations", "ansi-b30", "osha", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-outrigger-inspection-setup",
    title: "Crane Outrigger Inspection and Setup: Preventing the #1 Cause of Tip-Overs",
    excerpt: "Outrigger failure and improper setup cause more crane tip-overs than any other single factor. Complete guide to outrigger inspection criteria, proper deployment procedures, and ground bearing pressure calculations.",
    date: "March 26, 2026",
    readTime: "11 min read",
    category: "Safety",
    tags: ["safety", "inspection", "mobile-crane", "checklists"],
    author: "nolan-terry",
  },
  {
    slug: "third-party-crane-inspection",
    title: "Third-Party Crane Inspection: When You Need an Outside Inspector",
    excerpt: "When do you need a third-party crane inspector vs. in-house? Understand the regulatory triggers, insurance requirements, and business situations that mandate independent crane inspections.",
    date: "March 26, 2026",
    readTime: "11 min read",
    category: "Inspection",
    tags: ["inspection", "compliance", "safety", "certification"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-lift-plan-requirements",
    title: "Crane Lift Plan Requirements: What Every Contractor Must Document",
    excerpt: "Every crane lift needs a plan — but critical lifts require formal documentation that most contractors get wrong. Complete guide to lift plan requirements, critical lift thresholds, and what OSHA expects in your documentation.",
    date: "March 26, 2026",
    readTime: "12 min read",
    category: "Safety",
    tags: ["safety", "documentation", "compliance", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "conexpo-2026-crane-inspection-technology",
    title: "ConExpo 2026: Why Crane Inspection Is Finally Going Digital",
    excerpt: "ConExpo-CON/AGG 2026 is showcasing the most advanced crane technology ever built. But most crane companies still track inspections on paper. That disconnect is closing fast.",
    date: "March 9, 2026",
    readTime: "8 min read",
    category: "Industry",
    tags: ["industry", "technology", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "annual-crane-inspection-requirements",
    title: "Annual Crane Inspection Requirements: What OSHA and ANSI B30 Actually Require",
    excerpt: "There are three tiers of crane inspections — frequent, periodic, and annual. Most companies get the first two right and completely botch the annual. Here's what the standards actually say, who's qualified to perform them, and what you need to document.",
    date: "March 9, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "ansi-b30", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "qualified-vs-competent-person-crane",
    title: "Qualified Person vs. Competent Person: Who Can Inspect Your Crane?",
    excerpt: "OSHA uses these terms precisely — and they don't mean the same thing. If the wrong person is signing off on your inspections, those inspections are effectively invalid.",
    date: "March 9, 2026",
    readTime: "9 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "certification", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-maintenance-log-requirements",
    title: "Crane Maintenance Log Requirements: What OSHA Expects in Your Records",
    excerpt: "OSHA 1926.1417 has specific maintenance documentation requirements that most crane companies overlook — until an auditor or a plaintiff's attorney comes looking.",
    date: "March 9, 2026",
    readTime: "10 min read",
    category: "Compliance",
    tags: ["compliance", "osha", "maintenance", "documentation"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-rental-inspection-obligations",
    title: "Who's Responsible for Inspecting a Rented Crane? OSHA Rules Explained",
    excerpt: "OSHA's multi-employer worksite rules create complex inspection obligations for rented cranes. Both the rental company and the contractor can be cited.",
    date: "March 9, 2026",
    readTime: "10 min read",
    category: "Safety",
    tags: ["safety", "osha", "rental", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-record-retention",
    title: "How Long Must You Keep Crane Inspection Records? Retention Guide",
    excerpt: "Crane inspection record retention requirements under OSHA, ANSI B30, and state regulations. What to keep, how long, and why digital records eliminate retention risk.",
    date: "March 9, 2026",
    readTime: "8 min read",
    category: "Compliance",
    tags: ["compliance", "records", "documentation", "regulations"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-accident-investigation-documentation",
    title: "Crane Accident Investigation: Documentation That Protects Your Company",
    excerpt: "When a crane incident happens, what you document in the first 24 hours determines whether you face a standard citation or a willful violation. Covers OSHA reporting timelines, scene documentation, and how your inspection history becomes your defense.",
    date: "March 8, 2026",
    readTime: "13 min read",
    category: "Safety",
    tags: ["safety", "osha", "documentation", "penalties"],
    author: "cranecheck-team",
  },
  {
    slug: "rigging-inspection-requirements",
    title: "Rigging Inspection Requirements: Slings, Shackles, and Hardware",
    excerpt: "Complete OSHA rigging inspection requirements under 29 CFR 1926.251. Covers wire rope sling criteria, synthetic web sling checks, chain sling inspection, shackle load ratings, and removal-from-service standards.",
    date: "March 8, 2026",
    readTime: "11 min read",
    category: "Rigging",
    tags: ["rigging", "osha", "inspection", "safety"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-inspection-report-template",
    title: "Crane Inspection Report Template: What Inspectors Actually Need",
    excerpt: "Most crane inspection forms are missing critical fields. Learn what a compliant crane inspection report must contain, common documentation gaps that trigger OSHA citations, and why static templates create more risk than they solve.",
    date: "March 8, 2026",
    readTime: "10 min read",
    category: "Templates",
    tags: ["templates", "inspection", "documentation", "compliance"],
    author: "cranecheck-team",
  },
  {
    slug: "overhead-crane-inspection-frequency",
    title: "Overhead Crane Inspection Frequency: OSHA vs ASME Requirements",
    excerpt: "How often should you inspect overhead cranes? Break down daily, monthly, quarterly, and annual inspection schedules under OSHA 1910.179 and ASME B30.2, plus service classification guidance.",
    date: "March 8, 2026",
    readTime: "12 min read",
    category: "Compliance",
    tags: ["overhead-crane", "compliance", "osha", "inspection"],
    author: "cranecheck-team",
  },
  {
    slug: "crane-load-chart-documentation",
    title: "How to Document Crane Load Charts for OSHA Compliance",
    excerpt: "Complete guide to crane load chart documentation requirements. Learn rated capacity recording, boom length tracking, digital load chart management, and how to prevent citations with proper documentation systems.",
    date: "March 8, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["compliance", "load-charts", "documentation", "osha"],
    author: "cranecheck-team",
  },
  {
    slug: "mobile-crane-inspection-checklist",
    title: "Mobile Crane Inspection Checklist: Complete Field Guide",
    excerpt: "A comprehensive pre-operation inspection checklist for all-terrain, rough-terrain, and truck-mounted mobile cranes. Covers hydraulic systems, outriggers, load moment indicators, wire rope, and all OSHA-required inspection items for daily compliance.",
    date: "March 7, 2026",
    readTime: "11 min read",
    category: "Checklists",
    tags: ["mobile-crane", "checklists", "inspection", "osha"],
    author: "nolan-terry",
  },
  {
    slug: "crane-inspection-penalties-fines",
    title: "OSHA Crane Inspection Penalties: What Non-Compliance Actually Costs",
    excerpt: "The real financial impact of OSHA crane inspection violations in 2026. From $16,550 serious violations to $165,514 willful violations, plus real citation examples and how penalties compound when multiple cranes and violations are involved.",
    date: "March 6, 2026",
    readTime: "12 min read",
    category: "Compliance",
    tags: ["compliance", "penalties", "osha", "regulations"],
    author: "nolan-terry",
  },
  {
    slug: "tower-crane-inspection-requirements",
    title: "Tower Crane Inspection Requirements: Erection to Dismantling",
    excerpt: "Comprehensive guide to tower crane inspection requirements throughout the crane lifecycle. From foundation engineering review and pre-erection inspections to climbing procedures, monthly/annual inspections, and dismantling requirements under OSHA 29 CFR 1926 Subpart CC.",
    date: "March 5, 2026",
    readTime: "13 min read",
    category: "Regulations",
    tags: ["tower-crane", "regulations", "osha", "inspection"],
    author: "nolan-terry",
  },
  {
    slug: "crane-wire-rope-inspection-guide",
    title: "Crane Wire Rope Inspection: When to Replace and What to Look For",
    excerpt: "Comprehensive guide to crane wire rope inspection based on ASME B30.5 standards. Learn broken wire replacement thresholds, diameter reduction limits, corrosion assessment criteria, heat damage identification, and proper end connection inspection techniques.",
    date: "March 4, 2026",
    readTime: "12 min read",
    category: "Safety",
    tags: ["wire-rope", "safety", "inspection", "ansi-b30"],
    author: "nolan-terry",
  },
  {
    slug: "crane-operator-certification-requirements",
    title: "Crane Operator Certification Requirements: NCCCO, CIC, and State Rules",
    excerpt: "Complete guide to crane operator certification requirements under OSHA's 2026 mandate. Compare NCCCO, CIC-Crane, and NCCER programs, understand state-specific requirements, recertification timelines, and develop compliant operator qualification programs.",
    date: "March 3, 2026",
    readTime: "13 min read",
    category: "Compliance",
    tags: ["certification", "compliance", "osha", "construction"],
    author: "nolan-terry",
  },
  {
    slug: "osha-crane-inspection-requirements",
    title: "OSHA Crane Inspection Requirements: The Complete 2026 Guide",
    excerpt: "Everything you need to know about OSHA's crane inspection requirements under 29 CFR 1926.1412 and 29 CFR 1910.179 — inspection types, frequencies, documentation requirements, and how to stay compliant.",
    date: "March 1, 2026",
    readTime: "12 min read",
    category: "Compliance",
    tags: ["osha", "compliance", "inspection", "regulations"],
    author: "nolan-terry",
  },
  {
    slug: "daily-crane-inspection-checklist",
    title: "Daily Crane Inspection Checklist: What OSHA Actually Requires",
    excerpt: "A detailed breakdown of the OSHA-required daily crane inspection checklist items under 29 CFR 1926.1412(d). Know exactly what your operators need to check before every shift.",
    date: "February 22, 2026",
    readTime: "10 min read",
    category: "Checklists",
    tags: ["checklists", "osha", "inspection", "compliance"],
    author: "nolan-terry",
  },
  {
    slug: "crane-inspection-software-vs-paper",
    title: "Crane Inspection Software vs Paper Logs: Why Digital Wins",
    excerpt: "Paper crane inspection logs are a liability. Digital inspection software eliminates lost records, illegible handwriting, and audit-day panic. Here's the full comparison.",
    date: "February 15, 2026",
    readTime: "9 min read",
    category: "Technology",
    tags: ["technology", "inspection", "documentation", "compliance"],
    author: "nolan-terry",
  },
  {
    slug: "osha-crane-audit-preparation",
    title: "How to Prepare for an OSHA Crane Audit",
    excerpt: "OSHA crane audits don't have to be stressful. Learn what inspectors look for, which records they'll request, and how to be ready before they arrive.",
    date: "February 8, 2026",
    readTime: "11 min read",
    category: "Compliance",
    tags: ["audit", "osha", "compliance", "documentation"],
    author: "nolan-terry",
  },
  {
    slug: "29-cfr-1926-1412-explained",
    title: "29 CFR 1926.1412 Explained: Pre-Shift Crane Inspection Rules",
    excerpt: "A plain-English breakdown of 29 CFR 1926.1412 — the OSHA standard that governs crane inspections on construction sites. What it requires, who's responsible, and how to comply.",
    date: "February 1, 2026",
    readTime: "13 min read",
    category: "Regulations",
    tags: ["regulations", "osha", "construction", "inspection"],
    author: "nolan-terry",
  },
];

export function getPostsByAuthor(authorSlug: string): BlogPost[] {
  return POSTS.filter(p => p.author === authorSlug);
}
